recover password function
villacisJimmy/ultimategithubcourse pull request #1
Opened 2024-10-03 09:37 UTC by villacisJimmy

- HTML file
- Send email function
- Confirm password

2024-10-03 09:50 UTC, villacisJimmy commented on passwords.txt
> +mypass
Looks good!, but could leave "mypass" as "my pass"

2024-10-04 09:51 UTC, jota-villacis commented on passwords.txt
> +mypass
Looks good but could you edit "mypass" as "my pass"

2024-10-04 09:53 UTC, jota-villacis requested changes
Please update file passwords.txt

2024-10-04 10:02 UTC, villacisJimmy commented on passwords.txt
> +mypass
The file is already edited, could you checked it again

2024-10-04 10:06 UTC, jota-villacis approved these changes
LGTM 🚀

2024-10-04 10:09 UTC, merged